const api=window.PresentStudioApi, $=s=>document.querySelector(s);
const presentationId=new URLSearchParams(location.search).get("id")||"pres_demo";
const authToken=localStorage.getItem("presentStudio.accessToken")||"", socket=window.io?window.io():null;
let presentation,currentSlideIndex=0,canvas,saveTimer,shareUrl="",loading=false,mediaAssets=[],selectedPresenter="Self",uploadRequestId=0,retryUploadFile=null;
const W=1280,H=720;
function toast(m){const n=$("#toast");n.textContent=m;n.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove("show"),2600)}
function setShareLink(url,permission){shareUrl=url||"";const isPresenter=permission==="presenter",button=$("#openShareLink");$("#shareStatus").textContent=shareUrl;button.disabled=!shareUrl;button.querySelector("span").textContent=shareUrl?(isPresenter?"Open Presenter":"Open Audience"):"Open Link";button.setAttribute("aria-label",shareUrl?`Open ${isPresenter?"presenter":"audience"} link in a new tab`:"Open generated link in a new tab")}
function setShareError(message){setShareLink("","");$("#shareStatus").textContent=message}
function activeSlide(){return presentation.slides[currentSlideIndex]}
function ensure(s){s.canvas||={background:"#f8f4ea",elements:[]};s.canvas.elements||=[];s.canvas.transition||={type:"fade",duration_ms:500};if(!s.canvas.fabric&&!s.canvas.elements.some(x=>x.type==="text"))s.canvas.elements.push({id:"title",type:"text",text:s.title||"Untitled slide",x:18,y:30,width:64,fontSize:56,fontWeight:"600",color:"#171717",textAlign:"center"},{id:"subtitle",type:"text",text:"",x:18,y:52,width:64,fontSize:24,fontWeight:"600",color:"#171717",textAlign:"center"});return s}
function playback(){const s=ensure(presentation.slides[0]);return s.canvas.presentation_playback||=( {mode:"manual",interval_ms:5000,slide_ids:[],media_mode:"all",media_cycle:"all",media_interval_ms:5000,loop_videos:true})}
function text(item){return new fabric.Textbox(item.text||"",{id:item.id,left:(item.x||0)*12.8,top:(item.y||0)*7.2,width:(item.width||40)*12.8,fontSize:item.fontSize||42,fontWeight:item.fontWeight||"500",fontStyle:item.fontStyle||"normal",fontFamily:item.fontFamily||"Arial",fill:item.color||"#171717",textAlign:item.textAlign||"left"})}
function video(item){return new fabric.Rect({id:item.id,left:(item.x||0)*12.8,top:(item.y||0)*7.2,width:(item.width||40)*12.8,height:(item.height||30)*7.2,fill:"#1c1a16",stroke:"#d1a948",strokeWidth:4,rx:8,ry:8,mediaType:"video",src:item.src,full_bleed:item.full_bleed,loop:item.loop,muted:item.muted,fit:item.fit||"cover"})}
function image(item){fabric.Image.fromURL(item.src,o=>{o.set({id:item.id,mediaType:"image",src:item.src,audioSrc:item.audioSrc||"",audioName:item.audioName||"",full_bleed:item.full_bleed,loop:item.loop,muted:item.muted,fit:item.fit||"cover",left:(item.x||0)*12.8,top:(item.y||0)*7.2});o.scaleToWidth((item.width||40)*12.8);if(o.getScaledHeight()>(item.height||30)*7.2)o.scaleToHeight((item.height||30)*7.2);canvas.add(o);if(item.full_bleed)canvas.sendToBack(o);canvas.requestRenderAll()})}
function capture(){if(!presentation||loading)return;const s=ensure(activeSlide());s.canvas.background=canvas.backgroundColor||"#f8f4ea";s.canvas.fabric=canvas.toJSON(["id","mediaType","src","audioSrc","audioName","full_bleed","loop","muted","fit","builderAnimation","builderAnimationStart","builderAnimationDuration","builderAnimationDelay","builderAnimationDirection","builderAnimationOrder","hyperlink"]);const title=canvas.getObjects().find(o=>o.id==="title");if(title&&title.text.trim())s.title=title.text.trim()}
function load(){loading=true;const d=ensure(activeSlide()).canvas;if(d.fabric)canvas.loadFromJSON(d.fabric,()=>{canvas.backgroundColor=d.background||"#f8f4ea";canvas.renderAll();loading=false;panel()});else{canvas.clear();canvas.backgroundColor=d.background||"#f8f4ea";d.elements.forEach(x=>{if(x.type==="text")canvas.add(text(x));else if(x.type==="image")image(x);else if(x.type==="video")canvas.add(video(x))});canvas.requestRenderAll();loading=false;panel()}}
function esc(v){return String(v||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function renderUploadStatus(state,message){const status=$("#uploadStatus"),icons={success:"✓",error:"!",info:"•"};status.className="upload-status "+(state?"is-"+state:"");status.setAttribute("aria-busy",String(state==="uploading"));status.innerHTML='<span class="upload-status-line"><span class="upload-state-icon" aria-hidden="true">'+(icons[state]||"")+'</span><span class="upload-status-message">'+esc(message)+"</span>"+(state==="error"?'<button class="upload-retry" type="button">Retry</button>':"")+"</span>"+(state==="uploading"?'<span class="upload-progress" aria-hidden="true"><span class="upload-progress-bar"></span></span>':"");const retry=status.querySelector(".upload-retry");if(retry)retry.onclick=()=>{if(retryUploadFile)uploadFile(retryUploadFile)}}
function active(){return canvas.getActiveObject()}
function panel(){const o=active(),ok=o&&["textbox","text","i-text"].includes(o.type),isImage=o?.mediaType==="image";$("#editorPanel").hidden=!ok;$("#imageAudioPanel").hidden=!isImage;if(isImage){const audio=mediaAssets.filter(a=>a.mimeType.startsWith("audio/"));$("#imageAudio").innerHTML='<option value="">No linked audio</option>'+audio.map(a=>'<option value="'+esc(a.url)+'">'+esc(a.name)+"</option>").join("");$("#imageAudio").value=o.audioSrc||""}if(!ok)return;$("#selectionNote").textContent=o.id==="title"?"Title":o.id==="subtitle"?"Subtitle":"Text";$("#fontSize").value=o.fontSize||32;$("#textColor").value=o.fill||"#171717";$("#boldButton").classList.toggle("active",String(o.fontWeight)==="bold"||Number(o.fontWeight)>=700);$("#italicButton").classList.toggle("active",o.fontStyle==="italic")}
function renderList(){$("#slideList").innerHTML=presentation.slides.map((s,i)=>'<button class="slide-item '+(i===currentSlideIndex?"active":"")+'" type="button" data-index="'+i+'">'+esc(s.title||"Untitled slide")+"</button>").join("");$("#slideList").querySelectorAll("[data-index]").forEach(b=>b.onclick=()=>{capture();currentSlideIndex=Number(b.dataset.index);render()})}
function mediaLibrary(){$("#mediaCount").textContent=mediaAssets.length+" item"+(mediaAssets.length===1?"":"s");$("#mediaLibraryGrid").innerHTML=mediaAssets.map(a=>'<button class="media-library-item" type="button" data-asset="'+a.id+'">'+(a.mimeType.startsWith("image/")?'<img src="'+a.url+'" alt="">':'<span class="media-type-icon">'+(a.mimeType.startsWith("audio/")?"♫":"▷")+'</span>')+"<span>"+esc(a.name)+"</span></button>").join("");$("#mediaLibraryGrid").querySelectorAll("[data-asset]").forEach(b=>b.onclick=()=>addAsset(mediaAssets.find(a=>a.id===b.dataset.asset)))}
function syncPlayback(){const c=playback();$("#playbackMode").value=c.mode;$("#playbackInterval").value=c.interval_ms;$("#mediaMode").value=c.media_mode;$("#mediaCycle").value=c.media_cycle||"all";$("#mediaInterval").value=c.media_interval_ms||5000;$("#loopVideos").checked=c.loop_videos!==false;$("#playbackSlides").innerHTML=presentation.slides.map((s,i)=>'<label><input type="checkbox" data-play-slide="'+s.id+'" '+(c.slide_ids.includes(s.id)?"checked":"")+"> "+(i+1)+". "+esc(s.title)+"</label>").join("");$("#playbackSlides").querySelectorAll("[data-play-slide]").forEach(b=>b.onchange=()=>{c.slide_ids=[...$("#playbackSlides").querySelectorAll("[data-play-slide]:checked")].map(x=>x.dataset.playSlide);schedule()})}
function render(){const s=ensure(activeSlide()),count=String(currentSlideIndex+1).padStart(2,"0")+" / "+String(presentation.slides.length).padStart(2,"0");$("#presentationTitle").textContent=presentation.title;$("#slideCount").textContent=count;$("#canvasIndex").textContent=count;$("#pageLabel").textContent="Slide "+(currentSlideIndex+1)+" of "+presentation.slides.length;$("#transitionType").value=s.canvas.transition.type;$("#transitionDuration").value=s.canvas.transition.duration_ms;renderList();mediaLibrary();syncPlayback();load()}
function normalize(){presentation.slides.forEach((s,i)=>s.order=i+1)} async function save(){clearTimeout(saveTimer);capture();normalize();$("#modeLabel").textContent="Saving…";try{const r=await api.savePresentation(presentation);presentation=r.presentation;presentation.slides.forEach(ensure);playback();$("#modeLabel").textContent="Saved"}catch(e){$("#modeLabel").textContent="Save failed";toast(e.message);throw e}} function schedule(){if(loading)return;clearTimeout(saveTimer);saveTimer=setTimeout(()=>save().catch(()=>{}),600)}
function move(n){capture();currentSlideIndex=(currentSlideIndex+n+presentation.slides.length)%presentation.slides.length;render()} function addSlide(){capture();presentation.slides.splice(currentSlideIndex+1,0,ensure({id:"slide_"+Date.now(),order:0,title:"Slide "+(presentation.slides.length+1),canvas:{background:"#f8f4ea",elements:[]}}));currentSlideIndex++;normalize();render();schedule()} function duplicateSlide(){capture();const s=JSON.parse(JSON.stringify(activeSlide()));s.id="slide_"+Date.now();s.title+=" copy";presentation.slides.splice(currentSlideIndex+1,0,s);currentSlideIndex++;normalize();render();schedule()} function deleteSlide(){if(presentation.slides.length===1)return toast("A presentation needs at least one slide.");capture();const r=presentation.slides.splice(currentSlideIndex,1)[0];playback().slide_ids=playback().slide_ids.filter(id=>id!==r.id);currentSlideIndex=Math.min(currentSlideIndex,presentation.slides.length-1);render();schedule()}
function addAsset(a,announce=true){if(!a)return;if(a.mimeType.startsWith("audio/")){if(announce)renderUploadStatus("info",a.name+" is ready to link to an image.");panel();return}const full=$("#mediaFullBleed").checked,x={id:"media_"+Date.now(),type:a.mimeType.startsWith("image/")?"image":"video",src:a.url,x:full?0:30,y:full?0:30,width:full?100:40,height:full?100:30,full_bleed:full,loop:$("#loopVideos").checked,muted:true,fit:"cover"};if(x.type==="image")image(x);else canvas.add(video(x));canvas.requestRenderAll();if(announce)renderUploadStatus("info",a.name+" added to the current slide.");schedule()}
async function uploadFile(f){const requestId=++uploadRequestId;retryUploadFile=null;renderUploadStatus("uploading","Uploading… "+f.name);try{const r=await api.uploadMedia(f);mediaAssets.unshift(r.asset);addAsset(r.asset,false);mediaLibrary();if(requestId===uploadRequestId)renderUploadStatus("success",f.name+" uploaded successfully.")}catch(err){if(requestId!==uploadRequestId)return;retryUploadFile=f;const message=err.message.includes("Cloudinary")?"Media storage is not configured on this server.":err.message;renderUploadStatus("error",message)}}
async function upload(e){const f=e.target.files[0];e.target.value="";if(!f)return;if(!/^(image|video|audio)\//.test(f.type)&&!f.name.toLowerCase().endsWith(".mp3"))return toast("Choose an image, video, or audio file.");await uploadFile(f)}
function action(type){const o=active();if(!o)return toast("Select an element on the slide first.");if(type==="forward")canvas.bringForward(o);if(type==="backward")canvas.sendBackwards(o);if(type==="delete")canvas.remove(o);if(type==="duplicate")o.clone(c=>{c.set({left:(o.left||0)+32,top:(o.top||0)+32,id:(o.id||"element")+"_"+Date.now()});canvas.add(c);canvas.setActiveObject(c)});canvas.requestRenderAll();panel();schedule()}
function format(ch){const o=active();if(!o||!["textbox","text","i-text"].includes(o.type))return toast("Select a text element to format it.");Object.assign(o,ch);canvas.requestRenderAll();panel();schedule()}
function selectPresenter(name){if(!["Self","Partner"].includes(name))return;selectedPresenter=name;document.querySelectorAll(".presenter-option").forEach(button=>{const active=button.dataset.presenter===name;button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active))})}
async function start(){if(selectedPresenter==="Partner"){const partnerWindow=window.open("about:blank","_blank");if(partnerWindow)partnerWindow.opener=null;try{await save();const r=await api.createShareLink(presentation.id,"presenter");$("#sharePermission").value="presenter";setShareLink(r.url,r.permission);if(partnerWindow)partnerWindow.location.replace(r.url);else toast("Partner link created. Allow pop-ups or use Copy Link.")}catch(e){partnerWindow?.close();setShareError(e.message);toast(e.message)}return}try{await save();window.open("/controller.html?id="+encodeURIComponent(presentation.id),"_blank","noopener")}catch{}}
function bind(){canvas.on("selection:created",panel);canvas.on("selection:updated",panel);canvas.on("selection:cleared",panel);canvas.on("object:modified",schedule);canvas.on("text:changed",schedule);$("#fontSize").oninput=e=>format({fontSize:+e.target.value});$("#textColor").oninput=e=>format({fill:e.target.value});$("#fontFamily").onchange=e=>format({fontFamily:e.target.value});$("#boldButton").onclick=()=>format({fontWeight:(String(active()?.fontWeight)==="bold"||Number(active()?.fontWeight)>=700)?"normal":"bold"});$("#italicButton").onclick=()=>format({fontStyle:active()?.fontStyle==="italic"?"normal":"italic"});document.querySelectorAll("[data-align]").forEach(b=>b.onclick=()=>format({textAlign:b.dataset.align}));
$("#imageAudio").onchange=e=>{const o=active();if(o?.mediaType!=="image")return;const asset=mediaAssets.find(a=>a.url===e.target.value);o.set({audioSrc:asset?.url||"",audioName:asset?.name||""});schedule();$("#uploadStatus").textContent=asset?asset.name+" linked to the selected image.":"Linked audio removed."};
$("#transitionType").onchange=e=>{ensure(activeSlide()).canvas.transition.type=e.target.value;schedule()};$("#transitionDuration").onchange=e=>{ensure(activeSlide()).canvas.transition.duration_ms=+e.target.value;schedule()};$("#playbackMode").onchange=e=>{playback().mode=e.target.value;syncPlayback();schedule()};$("#playbackInterval").onchange=e=>{playback().interval_ms=+e.target.value;schedule()};$("#mediaMode").onchange=e=>{playback().media_mode=e.target.value;schedule()};$("#mediaCycle").onchange=e=>{playback().media_cycle=e.target.value;schedule()};$("#mediaInterval").onchange=e=>{playback().media_interval_ms=+e.target.value;schedule()};$("#loopVideos").onchange=e=>{playback().loop_videos=e.target.checked;schedule()};
document.querySelectorAll("[data-slide-prev]").forEach(b=>b.onclick=()=>move(-1));document.querySelectorAll("[data-slide-next]").forEach(b=>b.onclick=()=>move(1));$("#addSlide").onclick=addSlide;$("#duplicateSlide").onclick=duplicateSlide;$("#deleteSlide").onclick=deleteSlide;$("#renamePresentation").onclick=()=>{const v=prompt("Presentation title",presentation.title);if(v?.trim()){presentation.title=v.trim();render();schedule()}};$("#renameSlide").onclick=()=>{const v=prompt("Slide title",activeSlide().title);if(v?.trim()){activeSlide().title=v.trim();const t=canvas.getObjects().find(o=>o.id==="title");if(t)t.set("text",v.trim());render();schedule()}};
document.querySelectorAll('.presenter-option[data-presenter="Self"],.presenter-option[data-presenter="Partner"]').forEach(button=>button.onclick=()=>selectPresenter(button.dataset.presenter));
$("#bringForward").onclick=()=>action("forward");$("#sendBackward").onclick=()=>action("backward");$("#duplicateElement").onclick=()=>action("duplicate");$("#deleteElement").onclick=()=>action("delete");$("#generateLink").onclick=async()=>{setShareLink("","");try{await save();const r=await api.createShareLink(presentation.id,$("#sharePermission").value);setShareLink(r.url,r.permission)}catch(e){setShareError(e.message)}};$("#copyLink").onclick=async()=>{if(!shareUrl)return toast("Generate a link first.");try{await navigator.clipboard.writeText(shareUrl);toast("Share link copied.")}catch{$("#shareStatus").textContent=shareUrl}};$("#openShareLink").onclick=()=>{if(shareUrl)window.open(shareUrl,"_blank","noopener,noreferrer")};$("#startLive").onclick=start;$("#openAudience").onclick=()=>window.open("/screen.html?id="+encodeURIComponent(presentation.id),"_blank","noopener");document.querySelectorAll("[data-media-input]").forEach(i=>i.addEventListener("change",upload));$("#fileUpload").addEventListener("change",upload);$("[data-fullscreen]").onclick=()=>$(".canvas-card").requestFullscreen?.();
document.addEventListener("keydown",e=>{if((e.key==="Delete"||e.key==="Backspace")&&!active()?.isEditing){e.preventDefault();action("delete")}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="d"){e.preventDefault();action("duplicate")}})}
async function init(){if(!window.fabric)throw new Error("The editor canvas library did not load.");canvas=new fabric.Canvas("fabricCanvas",{width:W,height:H,preserveObjectStacking:true,selection:true});bind();const [r,library]=await Promise.all([api.getPresentation(presentationId),api.listMedia().catch(()=>({assets:[]}))]);presentation=r.presentation;mediaAssets=library.assets||[];if(!presentation.slides.length)addSlide();presentation.slides.forEach(ensure);playback();render();$("#modeLabel").textContent="Ready";socket?.emit("join_presentation",{presentationId:presentation.id})} init().catch(e=>{$("#modeLabel").textContent="Error";toast(e.message)});
