const api = window.PresentStudioApi;
const presentationId = new URLSearchParams(location.search).get("id") || "pres_demo";
const socket = window.io ? window.io() : null;
const authToken = localStorage.getItem("presentStudio.accessToken") || "";
const $ = (selector) => document.querySelector(selector);
let presentation; let currentSlideIndex = 0; let selected = "title"; let saveTimer; let shareUrl = ""; let mediaAssets = [];
const titleElement = $("#titleElement"), subtitleElement = $("#subtitleElement"), slideList = $("#slideList"), toast = $("#toast");
const defaultElement = (id, text, y, size) => ({ id, type: "text", text, x: 18, y, width: 64, fontSize: size, fontWeight: "600", fontStyle: "normal", fontFamily: "Arial, sans-serif", color: "#171717", textAlign: "center" });
function activeSlide() { return presentation.slides[currentSlideIndex]; }
function ensure(slide) { slide.canvas ||= { background: "#f8f4ea", elements: [] }; slide.canvas.elements ||= []; slide.canvas.transition ||= { type: "fade", duration_ms: 500 }; if (!slide.canvas.elements.find(x => x.id === "title")) slide.canvas.elements.push(defaultElement("title", slide.title || "Untitled slide", 30, 56)); if (!slide.canvas.elements.find(x => x.id === "subtitle")) slide.canvas.elements.push(defaultElement("subtitle", "", 52, 24)); return slide; }
function playback() { presentation.playback ||= { mode: "manual", interval_ms: 5000, slide_ids: [], media_mode: "all", media_cycle: "all", media_interval_ms: 5000, loop_videos: true }; return presentation.playback; }
function element(id) { return ensure(activeSlide()).canvas.elements.find(x => x.id === id); }
function showToast(message) { if (!toast) return; toast.textContent = message; toast.classList.add("show"); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove("show"), 2600); }
function setMode(message) { $("#modeLabel").textContent = message; }
function escape(value) { return String(value || "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[c]); }
function apply(node, data) { node.textContent = data.text || ""; Object.assign(node.style, { fontSize: `${data.fontSize || 32}px`, fontWeight: data.fontWeight || "500", fontStyle: data.fontStyle || "normal", fontFamily: data.fontFamily || "Arial, sans-serif", color: data.color || "#171717", textAlign: data.textAlign || "center" }); }
function render() { const slide = ensure(activeSlide()); apply(titleElement, element("title")); apply(subtitleElement, element("subtitle")); $("#presentationTitle").textContent = presentation.title; const counter = `${String(currentSlideIndex + 1).padStart(2, "0")} / ${String(presentation.slides.length).padStart(2, "0")}`; $("#slideCount").textContent = counter; $("#canvasIndex").textContent = counter; $("#pageLabel").textContent = `Slide ${currentSlideIndex + 1} of ${presentation.slides.length}`; $("#transitionType").value = slide.canvas.transition.type; $("#transitionDuration").value = String(slide.canvas.transition.duration_ms); syncPlaybackPanel(); renderList(); renderMediaLibrary(); select(selected); }
function renderList() { slideList.innerHTML = presentation.slides.map((slide, index) => `<button class="slide-item ${index === currentSlideIndex ? "active" : ""}" type="button" data-index="${index}">${escape(slide.title || "Untitled slide")}</button>`).join(""); slideList.querySelectorAll("[data-index]").forEach(button => button.onclick = () => { currentSlideIndex = Number(button.dataset.index); render(); }); }
function syncPlaybackPanel() { const config = playback(); $("#playbackMode").value = config.mode; $("#playbackInterval").value = String(config.interval_ms); $("#mediaMode").value = config.media_mode; $("#mediaCycle").value = config.media_cycle || "all"; $("#mediaInterval").value = String(config.media_interval_ms || 5000); $("#loopVideos").checked = config.loop_videos !== false; $("#playbackSlides").innerHTML = presentation.slides.map((slide, index) => `<label><input type="checkbox" data-play-slide="${slide.id}" ${config.slide_ids.includes(slide.id) ? "checked" : ""}> ${index + 1}. ${escape(slide.title)}</label>`).join(""); $("#playbackSlides").querySelectorAll("[data-play-slide]").forEach(box => box.onchange = () => { config.slide_ids = [...$("#playbackSlides").querySelectorAll("[data-play-slide]:checked")].map(input => input.dataset.playSlide); scheduleSave(); }); }
function renderMediaLibrary() { $("#mediaCount").textContent = `${mediaAssets.length} item${mediaAssets.length === 1 ? "" : "s"}`; $("#mediaLibraryGrid").innerHTML = mediaAssets.map(asset => `<button class="media-library-item" type="button" data-asset="${asset.id}">${asset.mimeType.startsWith("image/") ? `<img src="${asset.url}" alt="">` : "<span class=\"media-type-icon\">▷</span>"}<span>${escape(asset.name)}</span></button>`).join(""); $("#mediaLibraryGrid").querySelectorAll("[data-asset]").forEach(button => button.onclick = () => addAsset(mediaAssets.find(asset => asset.id === button.dataset.asset))); }
function select(id) { selected = id; [titleElement, subtitleElement].forEach(node => node.classList.toggle("is-selected", node.id === `${id}Element`)); const data = element(id); $("#editorPanel").hidden = false; $("#selectionNote").textContent = id === "title" ? "Title" : "Subtitle"; $("#fontSize").value = data.fontSize || 32; $("#textColor").value = data.color || "#171717"; $("#boldButton").classList.toggle("active", Number(data.fontWeight) >= 700 || data.fontWeight === "bold"); $("#italicButton").classList.toggle("active", data.fontStyle === "italic"); }
function syncText() { const data = element(selected); const node = selected === "title" ? titleElement : subtitleElement; data.text = node.textContent; if (selected === "title") activeSlide().title = data.text || "Untitled slide"; scheduleSave(); }
function normalizeOrders() { presentation.slides.forEach((slide, index) => slide.order = index + 1); }
function scheduleSave() { setMode("Saving…"); clearTimeout(saveTimer); saveTimer = setTimeout(async () => { normalizeOrders(); try { const saved = await api.savePresentation(presentation); presentation = saved.presentation; presentation.slides.forEach(ensure); playback(); setMode("Saved"); } catch (error) { setMode("Save failed"); showToast(error.message); } }, 600); }
function go(delta) { currentSlideIndex = (currentSlideIndex + delta + presentation.slides.length) % presentation.slides.length; render(); }
function addSlide() { presentation.slides.splice(currentSlideIndex + 1, 0, ensure({ id: `slide_${Date.now()}`, order: 0, title: `Slide ${presentation.slides.length + 1}`, canvas: { background: "#f8f4ea", elements: [] } })); currentSlideIndex++; normalizeOrders(); render(); scheduleSave(); }
function duplicateSlide() { const copy = JSON.parse(JSON.stringify(activeSlide())); copy.id = `slide_${Date.now()}`; copy.title = `${copy.title} copy`; presentation.slides.splice(currentSlideIndex + 1, 0, copy); currentSlideIndex++; normalizeOrders(); render(); scheduleSave(); }
function deleteSlide() { if (presentation.slides.length === 1) return showToast("A presentation needs at least one slide."); const removed = presentation.slides.splice(currentSlideIndex, 1)[0]; playback().slide_ids = playback().slide_ids.filter(id => id !== removed.id); currentSlideIndex = Math.min(currentSlideIndex, presentation.slides.length - 1); normalizeOrders(); render(); scheduleSave(); }
function addAsset(asset) { if (!asset) return; const fullBleed = $("#mediaFullBleed").checked; const item = { id: `media_${Date.now()}`, type: asset.mimeType.startsWith("image/") ? "image" : "video", src: asset.url, x: fullBleed ? 0 : 30, y: fullBleed ? 0 : 30, width: fullBleed ? 100 : 40, height: fullBleed ? 100 : 30, full_bleed: fullBleed, loop: $("#loopVideos").checked, muted: true, fit: "cover" }; ensure(activeSlide()).canvas.elements.push(item); $("#uploadStatus").textContent = `${asset.name} added to the current slide.`; scheduleSave(); }
async function upload(event) { const file = event.target.files[0]; event.target.value = ""; if (!file) return; if (!/^(image|video)\//.test(file.type)) return showToast("Choose an image or video file."); $("#uploadStatus").textContent = `Uploading ${file.name}…`; try { const { asset } = await api.uploadMedia(file); mediaAssets.unshift(asset); addAsset(asset); renderMediaLibrary(); } catch (error) { $("#uploadStatus").textContent = error.message.includes("Cloudinary") ? "Media storage is not configured on this server." : error.message; } }
async function createShare() { try { const result = await api.createShareLink(presentation.id, "viewer"); shareUrl = result.url; $("#shareStatus").textContent = result.url; } catch (error) { $("#shareStatus").textContent = error.message; } }
function startLive() { socket?.emit("slide_changed", { presentationId: presentation.id, slideId: activeSlide().id, authToken }); window.open(`/present.html?id=${encodeURIComponent(presentation.id)}`, "_blank", "noopener"); }
function bind() {
  titleElement.addEventListener("focus", () => select("title")); subtitleElement.addEventListener("focus", () => select("subtitle")); titleElement.addEventListener("input", syncText); subtitleElement.addEventListener("input", syncText);
  $("#fontSize").oninput = event => { element(selected).fontSize = Number(event.target.value); render(); scheduleSave(); }; $("#textColor").oninput = event => { element(selected).color = event.target.value; render(); scheduleSave(); }; $("#boldButton").onclick = () => { const data = element(selected); data.fontWeight = Number(data.fontWeight) >= 700 ? "500" : "800"; render(); scheduleSave(); }; $("#italicButton").onclick = () => { const data = element(selected); data.fontStyle = data.fontStyle === "italic" ? "normal" : "italic"; render(); scheduleSave(); }; $("#fontFamily").onchange = event => { element(selected).fontFamily = event.target.value; render(); scheduleSave(); }; document.querySelectorAll("[data-align]").forEach(button => button.onclick = () => { element(selected).textAlign = button.dataset.align; render(); scheduleSave(); });
  $("#transitionType").onchange = event => { ensure(activeSlide()).canvas.transition.type = event.target.value; scheduleSave(); }; $("#transitionDuration").onchange = event => { ensure(activeSlide()).canvas.transition.duration_ms = Number(event.target.value); scheduleSave(); }; $("#playbackMode").onchange = event => { playback().mode = event.target.value; syncPlaybackPanel(); scheduleSave(); }; $("#playbackInterval").onchange = event => { playback().interval_ms = Number(event.target.value); scheduleSave(); }; $("#mediaMode").onchange = event => { playback().media_mode = event.target.value; scheduleSave(); }; $("#mediaCycle").onchange = event => { playback().media_cycle = event.target.value; scheduleSave(); }; $("#mediaInterval").onchange = event => { playback().media_interval_ms = Number(event.target.value); scheduleSave(); }; $("#loopVideos").onchange = event => { playback().loop_videos = event.target.checked; scheduleSave(); };
  document.querySelectorAll("[data-slide-prev]").forEach(button => button.onclick = () => go(-1)); document.querySelectorAll("[data-slide-next]").forEach(button => button.onclick = () => go(1)); $("#addSlide").onclick = addSlide; $("#duplicateSlide").onclick = duplicateSlide; $("#deleteSlide").onclick = deleteSlide; $("#renamePresentation").onclick = () => { const value = prompt("Presentation title", presentation.title); if (value?.trim()) { presentation.title = value.trim(); render(); scheduleSave(); } }; $("#renameSlide").onclick = () => { const value = prompt("Slide title", activeSlide().title); if (value?.trim()) { activeSlide().title = value.trim(); element("title").text = value.trim(); render(); scheduleSave(); } };
  $("#generateLink").onclick = createShare; $("#copyLink").onclick = async () => { if (!shareUrl) return showToast("Generate a link first."); try { await navigator.clipboard.writeText(shareUrl); showToast("Share link copied."); } catch { $("#shareStatus").textContent = shareUrl; } }; $("#startLive").onclick = startLive; $("#openAudience").onclick = () => window.open(`/present.html?id=${encodeURIComponent(presentation.id)}`, "_blank", "noopener"); document.querySelectorAll("[data-media-input]").forEach(input => input.addEventListener("change", upload)); $("#fileUpload").addEventListener("change", upload);
  $("#generateAi").onclick = async () => { const prompt = $("#aiPrompt").value.trim(); if (!prompt) return; try { const result = await api.generateAiSlide(prompt); element("title").text = result.title || element("title").text; element("subtitle").text = result.subtitle || element("subtitle").text; activeSlide().title = element("title").text; render(); scheduleSave(); } catch { $("#aiStatus").textContent = "AI generation is unavailable on this server."; } }; document.querySelectorAll(".presenter-option").forEach(button => button.onclick = () => $("#aiPanel").hidden = button.dataset.presenter !== "AI"); $("[data-fullscreen]").onclick = () => $(".canvas-card").requestFullscreen?.();
}
async function init() { bind(); const result = await api.getPresentation(presentationId); presentation = result.presentation; if (!presentation.slides.length) addSlide(); presentation.slides.forEach(ensure); playback(); render(); setMode("Ready"); socket?.emit("join_presentation", { presentationId: presentation.id }); }
init().catch(error => { setMode("Error"); showToast(error.message); });
