const api = window.PresentStudioApi;
const params = new URLSearchParams(location.search);
const presentationId = params.get("id") || "pres_demo";
const shareToken = params.get("token") || "";
const authToken = localStorage.getItem("presentStudio.accessToken") || "";
const socket = window.io ? window.io({ reconnection: true, reconnectionAttempts: 5, reconnectionDelay: 700 }) : null;
let canvas;
const $ = (id) => document.getElementById(id);
let presentation; let permission = "viewer"; let currentSlideIndex = 0; let autoplayTimer; let mediaTimer; let mediaIndex = 0; let autoplayRunning = false; let audioEnabled = true;
function activeSlide() { return presentation.slides[currentSlideIndex]; }
function playback() { return presentation.slides[0]?.canvas?.presentation_playback || { mode: "manual", interval_ms: 5000, slide_ids: [], media_mode: "all", media_cycle: "all", media_interval_ms: 5000, loop_videos: true }; }
function setVisible(element, visible) { if (element) element.hidden = !visible; }
function setStatus(message) { $("presentStatus").textContent = message; }
function textObject(item) { return new fabric.Textbox(item.text || "", { left: (item.x || 0) * 12.8, top: (item.y || 0) * 7.2, width: (item.width || 40) * 12.8, fontSize: item.fontSize || 42, fontWeight: item.fontWeight || "500", fontStyle: item.fontStyle || "normal", fontFamily: item.fontFamily || "Arial", fill: item.color || "#171717", textAlign: item.textAlign || "left", selectable: false, evented: false }); }
function mediaItems(slide) {
  const config = playback();
  const legacy = (slide.canvas?.elements || []).filter(item => ["image", "video"].includes(item.type));
  const fabricVideos = (slide.canvas?.fabric?.objects || []).filter(item => item.mediaType === "video").map(item => ({
    type: "video", src: item.src, full_bleed: item.full_bleed,
    x: ((item.left || 0) / 1280) * 100, y: ((item.top || 0) / 720) * 100,
    width: (((item.width || 0) * (item.scaleX || 1)) / 1280) * 100,
    height: (((item.height || 0) * (item.scaleY || 1)) / 720) * 100,
    loop: item.loop, muted: item.muted, fit: item.fit || "contain"
  }));
  return [...legacy, ...fabricVideos].filter(item => config.media_mode === "all" || config.media_mode === `${item.type}s`);
}
function renderMedia(slide) { const layer = $("presentMedia"); layer.replaceChildren(); const config = playback(); let items = mediaItems(slide); if (items.length > 1 && config.media_cycle === "sequential") items = [items[mediaIndex % items.length]]; if (items.length > 1 && config.media_cycle === "random") items = [items[Math.floor(Math.random() * items.length)]]; items.forEach(item => { const node = document.createElement(item.type === "video" ? "video" : "img"); node.src = item.src; node.className = `slide-media ${item.full_bleed ? "full-bleed" : ""}`; node.style.left = `${item.x || 0}%`; node.style.top = `${item.y || 0}%`; node.style.width = `${item.width || 100}%`; node.style.height = `${item.height || 100}%`; node.style.objectFit = item.fit || "contain"; if (item.type === "video") Object.assign(node, { autoplay: true, muted: item.muted === true || !audioEnabled, loop: config.loop_videos !== false && item.loop !== false, playsInline: true, controls: permission === "presenter" && !item.full_bleed }); layer.append(node); if (item.type === "video") node.play().catch(() => { node.muted = true; audioEnabled = false; syncAudioButton(); node.play().catch(() => {}); }); }); const track=slide.canvas?.audio; if(track?.src){const audio=document.createElement("audio");audio.src=track.src;audio.dataset.slideMusic="true";Object.assign(audio,{autoplay:true,muted:!audioEnabled,loop:track.loop!==false,playsInline:true});layer.append(audio);audio.play().catch(()=>{audio.muted=true;audioEnabled=false;syncAudioButton();audio.play().catch(()=>{})})} const hasAudio=items.some(item=>item.type==="video")||Boolean(track?.src); setVisible($("audioToggle"),hasAudio); syncAudioButton(); }
function syncAudioButton() { const button = $("audioToggle"); if (!button) return; button.textContent = audioEnabled ? "🔊 Mute audio" : "🔇 Enable audio"; button.setAttribute("aria-label", audioEnabled ? "Mute presentation audio" : "Enable presentation audio"); }
function toggleAudio() { audioEnabled = !audioEnabled; const button = $("audioToggle"); button.textContent = audioEnabled ? "🔊 Mute audio" : "🔇 Enable audio"; button.setAttribute("aria-label", audioEnabled ? "Mute presentation audio" : "Enable presentation audio"); document.querySelectorAll("#presentMedia video, #presentMedia audio").forEach(media => { media.muted = !audioEnabled; if (audioEnabled) media.play().catch(() => { audioEnabled = false; media.muted = true; button.textContent = "🔇 Enable audio"; }); }); }
function animate(slide) { const frame = $("presentFrame"); const config = slide.canvas?.transition || { type: "fade", duration_ms: 500 }; frame.style.setProperty("--transition-duration", `${config.duration_ms || 500}ms`); frame.classList.remove("transition-fade", "transition-fade-left", "transition-fade-right", "transition-fade-up", "transition-fade-down", "transition-slide", "transition-push-left", "transition-push-right", "transition-push-up", "transition-push-down", "transition-morph", "transition-morph-left", "transition-morph-right", "transition-morph-up", "transition-morph-down", "transition-zoom"); if (config.type && config.type !== "none") requestAnimationFrame(() => { frame.classList.add(`transition-${config.type}`); setTimeout(() => frame.classList.remove(`transition-${config.type}`), config.duration_ms || 500); }); }
function animateObjects() { canvas.getObjects().forEach(object => { const type = object.animation || "none"; if (type === "none") return; const duration = Math.max(100, Math.min(5000, Number(object.animationDuration) || 600)); const delay = Math.max(0, Math.min(5000, Number(object.animationDelay) || 0)); const finalState = { opacity: object.opacity ?? 1, left: object.left || 0, top: object.top || 0, scaleX: object.scaleX || 1, scaleY: object.scaleY || 1 }; const startState = {}; if (type === "fade") Object.assign(startState, { opacity: 0 }); if (type === "zoom") Object.assign(startState, { opacity: 0, scaleX: finalState.scaleX * 0.78, scaleY: finalState.scaleY * 0.78 }); if (type === "fly") Object.assign(startState, { opacity: 0, left: finalState.left - 140 }); if (type === "rise") Object.assign(startState, { opacity: 0, top: finalState.top + 90 }); if (type === "wipe") Object.assign(startState, { opacity: 0, scaleX: finalState.scaleX * 0.08 }); object.set(startState); setTimeout(() => { Object.entries(finalState).forEach(([key, value]) => object.animate(key, value, { duration, easing: fabric.util.ease.easeOutCubic, onChange: canvas.renderAll.bind(canvas), onComplete: () => { object.set(finalState); canvas.requestRenderAll(); } })); }, delay); }); }
function setMediaCycle() { clearInterval(mediaTimer); mediaIndex = 0; const config = playback(); if (["sequential", "random"].includes(config.media_cycle) && mediaItems(activeSlide()).length > 1) mediaTimer = setInterval(() => { mediaIndex += 1; renderMedia(activeSlide()); }, Number(config.media_interval_ms) || 5000); }
function sanitizeFabricScene(scene) { (scene.objects || []).forEach(object => { if (object.textBaseline === "alphabetical") object.textBaseline = "alphabetic"; }); return scene; }
function renderSlide() { const slide = activeSlide(); const data = slide.canvas || {}; canvas.clear(); canvas.backgroundColor = data.background || "#f8f4ea"; const done = () => { canvas.getObjects().forEach(object => { object.selectable = false; object.evented = false; }); canvas.renderAll(); animateObjects(); }; if (data.fabric) { const scene = sanitizeFabricScene(JSON.parse(JSON.stringify(data.fabric))); scene.objects = (scene.objects || []).filter(object => object.mediaType !== "video"); canvas.loadFromJSON(scene, done); } else { (data.elements || []).filter(item => item.type === "text").forEach(item => canvas.add(textObject(item))); done(); } renderMedia(slide); setMediaCycle(); animate(slide); $("slideCounter").textContent = `${currentSlideIndex + 1} / ${presentation.slides.length}`; setStatus(`${presentation.title} · ${permission === "presenter" ? "Live presenter" : "Live audience"}`); }
function emitSlide() { socket?.emit("slide_changed", { presentationId: presentation.id, slideId: activeSlide().id, authToken, shareToken }); }
function nextAutoplayIndex() { const config = playback(); if (config.mode === "random") return Math.floor(Math.random() * presentation.slides.length); if (config.mode === "selected") { const selected = presentation.slides.map((slide, index) => config.slide_ids.includes(slide.id) ? index : -1).filter(index => index >= 0); if (selected.length) return selected[(selected.indexOf(currentSlideIndex) + 1 + selected.length) % selected.length]; } return (currentSlideIndex + 1) % presentation.slides.length; }
function go(delta) { if (permission !== "presenter") return; currentSlideIndex = delta === 1 && autoplayRunning ? nextAutoplayIndex() : (currentSlideIndex + delta + presentation.slides.length) % presentation.slides.length; renderSlide(); emitSlide(); }
function setAutoplay(running) { const canAutoplay = permission === "presenter" && playback().mode !== "manual"; autoplayRunning = Boolean(running && canAutoplay); clearInterval(autoplayTimer); if (autoplayRunning) autoplayTimer = setInterval(() => go(1), Number(playback().interval_ms) || 5000); const button = $("autoplayToggle"); button.textContent = autoplayRunning ? "Stop auto play" : canAutoplay ? "Start auto play" : "Auto play: manual"; button.disabled = !canAutoplay; }
function showError(message) { setVisible($("presentLoading"), false); setVisible($("presentStage"), false); setVisible($("presentError"), true); $("errorMessage").textContent = message; }
async function endLive() {
  if (permission !== "presenter") return;
  socket?.emit("end_session", { presentationId: presentation.id, authToken, shareToken });
  if (!authToken) return;
  try { await api.endLiveSession(presentation.id); } catch (error) { showError(error.message); }
}
function setupSocket() { if (!socket) return; const joinRoom=()=>socket.emit("join_presentation",{presentationId:presentation.id}); socket.on("connect",joinRoom); socket.on("active_slide_changed",event=>{const found=presentation.slides.findIndex(slide=>slide.id===event.slideId);if(found>=0){currentSlideIndex=found;renderSlide()}}); socket.on("presentation_media_changed",event=>{const found=presentation.slides.findIndex(slide=>slide.id===event.slideId);if(found>=0){currentSlideIndex=found;renderSlide()}}); socket.on("presentation_media_control",event=>{document.querySelectorAll("#presentMedia video, #presentMedia audio").forEach(media=>{if(event.action==="toggle")media.paused?media.play().catch(()=>{}):media.pause();if(event.action==="replay"){media.currentTime=0;media.play().catch(()=>{})}if(event.action==="stop")media.pause()})}); socket.on("presentation_updated",event=>{if(event.presentationId!==presentation.id||!event.presentation)return;const currentId=presentation.slides[currentSlideIndex]?.id;presentation=event.presentation;const found=presentation.slides.findIndex(slide=>slide.id===(event.activeSlideId||currentId));currentSlideIndex=found>=0?found:0;renderSlide();setAutoplay(autoplayRunning)}); socket.on("presentation_deleted",event=>{if(event.presentationId===presentation.id){setAutoplay(false);showError("This presentation has been deleted.")}}); socket.on("presenter_rejected",event=>showError(event.message||"Presenter permission required.")); socket.on("session_ended",()=>{setAutoplay(false);showError("This live session has ended.")}); if(socket.connected)joinRoom(); }
async function init() { if (!window.fabric) throw new Error("Fabric.js could not be loaded. Check the presentation's network access and reload."); canvas = new fabric.StaticCanvas("presentCanvas", { width: 1280, height: 720, selection: false }); const result = await api.getPresentation(presentationId, shareToken); presentation = result.presentation; permission = result.permission || "viewer"; if (!presentation.slides.length) throw new Error("This presentation has no slides."); const live = await api.getLiveSession(presentation.id); const liveIndex = presentation.slides.findIndex(slide => slide.id === live.activeSlideId); if (liveIndex >= 0) currentSlideIndex = liveIndex; const presenter = permission === "presenter"; setVisible($("presentControls"), presenter); $("presenterBadge").textContent = presenter ? "Presenter Mode" : "Audience View"; setVisible($("presenterBadge"), true); $("previousSlide").onclick = () => go(-1); $("nextSlide").onclick = () => go(1); $("autoplayToggle").onclick = () => setAutoplay(!autoplayRunning); $("audioToggle").onclick = toggleAudio; $("endLive").onclick = endLive; document.addEventListener("keydown", event => { if (event.key.toLowerCase() === "f") $("fullscreenToggle").click(); if (event.key === "ArrowLeft") go(-1); if (event.key === "ArrowRight") go(1); }); $("fullscreenToggle").onclick = () => document.fullscreenElement ? document.exitFullscreen() : $("presentStage").requestFullscreen(); setVisible($("presentLoading"), false); setVisible($("presentStage"), true); renderSlide(); setAutoplay(playback().mode !== "manual"); setupSocket(); }
init().catch(error => showError(error.message));
